apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-myapp-custom-config
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'  # Feel free to change to another SMTP server
      smtp_from: 'example@gmail.com'  # The email address to send from
      smtp_auth_username: 'example@gmail.com'  # Same as the address above
      smtp_auth_password: {{ .Values.alertmanager.smtpPassword | quote }}
      smtp_require_tls: true
    
    route:
      receiver: 'null'                      # Default receiver
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 12h
      routes:
        - match:
            alertname: TooManyRequests      # Our alert from our prometheus rule
          receiver: 'devs'                 

    receivers:
      - name: 'null'
      - name: 'devs'
        email_configs:
          - to: 'example@gmail.com'    # Change email address to your desired recipient
            send_resolved: true