{{- if .Values.app.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "myapp.componentName" (dict "root" . "component" "app-ingress") }}
  labels:
    {{- include "myapp.componentLabels" (dict "root" . "component" "app") | nindent 4 }}
  {{- with .Values.app.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  rules:
    {{- range .Values.app.ingress.hosts }}
      {{- if .enabled }}
      - host: {{ .host | quote }}
        http:
          paths:
            - path: {{ .path | default "/" }}
              pathType: Prefix
              backend:
                service:
                  name: {{ include "myapp.appServiceName" $ }}
                  port:
                    number: {{ $.Values.app.service.port }}
      {{- end }}
      {{- end }}
  tls:
    {{- range .Values.app.ingress.hosts }}
      {{- if and .enabled .tlsSecretName }}
      - hosts:
          - {{ .host | quote }}
        secretName: {{ .tlsSecretName }}
      {{- end }}
      {{- end }}
  {{- end }}