apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.appServiceName" . }}
  labels:
    {{- include "myapp.componentLabels" (dict "root" . "component" "app") | nindent 4 }}
  {{- with .Values.app.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.app.service.type }}
  selector:
    {{- include "myapp.componentSelectorLabels" (dict "root" . "component" "app") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TCP

