apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.appConfigMapName" . }}
  labels:
    {{- include "myapp.componentLabels" (dict "root" . "component" "app") | nindent 4 }}
data:

  MODEL_HOST: "http://{{ .Values.model.name }}:{{ .Values.model.service.port }}"

  PORT: {{ .Values.app.service.targetPort | quote }}
