{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.grafanaName" . }}
  labels:
    {{- include "myapp.componentLabels" (dict "root" . "component" "grafana") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "myapp.componentSelectorLabels" (dict "root" . "component" "grafana") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "myapp.componentSelectorLabels" (dict "root" . "component" "grafana") | nindent 8 }}
    spec:
      containers:
        - name: grafana
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.adminUser | quote }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.adminPassword | quote }}
            - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
              value: /var/lib/grafana/dashboards/app-metrics-dashboard.json
          ports:
            - name: http
              containerPort: {{ .Values.grafana.service.port }}
              protocol: TCP
          volumeMounts:
            - name: grafana-dashboards
              mountPath: /var/lib/grafana/dashboards
            - name: grafana-provisioning
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
              subPath: dashboards.yaml

            - name: grafana-provisioning
              mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
              subPath: datasources.yaml

          {{- with .Values.grafana.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: grafana-dashboards
          configMap:
            name: {{ include "myapp.grafanaDashboardsName" . }}
        - name: grafana-provisioning
          configMap:
            name: {{ include "myapp.grafanaProvisioningName" . }}
  {{- end }}