apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.modelServiceName" . }}
  labels:
    {{- include "myapp.componentLabels" (dict "root" . "component" "model") | nindent 4 }}
spec:
  type: {{ .Values.model.service.type }}
  selector:
    {{- include "myapp.componentSelectorLabels" (dict "root" . "component" "model") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.model.service.port }}
      targetPort: {{ .Values.model.service.targetPort }}
      protocol: TCP