apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.modelConfigMapName" . }}
  labels:
    {{- include "myapp.componentLabels" (dict "root" . "component" "model") | nindent 4 }}
data:
  PORT: {{ .Values.model.service.targetPort | quote }}