{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.componentName" (dict "root" . "component" "prometheus-svc") }}
  labels:
    {{- include "myapp.componentLabels" (dict "root" . "component" "prometheus") | nindent 4 }}
spec:
  type: {{ .Values.prometheus.service.type }}
  selector:
    {{- include "myapp.componentSelectorLabels" (dict "root" . "component" "prometheus") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.prometheus.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}

