{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.prometheusCfgName" . }}
  labels:
    {{- include "myapp.componentLabels" (dict "root" . "component" "prometheus") | nindent 4 }}
data:
  prometheus.yml: |
    {{- tpl (.Files.Get "prometheus/prometheus-config.yaml") . | nindent 4 }}
  alerting-rules.yml: |
    {{- tpl (.Files.Get "prometheus/alerting-rules.yaml") . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.prometheusName" . }}
  labels:
    {{- include "myapp.componentLabels" (dict "root" . "component" "prometheus") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "myapp.componentSelectorLabels" (dict "root" . "component" "prometheus") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "myapp.componentSelectorLabels" (dict "root" . "component" "prometheus") | nindent 8 }}
    spec:
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.enable-lifecycle"
          ports:
            - containerPort: {{ .Values.prometheus.service.port }}
              name: http
          volumeMounts:
            - name: prom-config
              mountPath: /etc/prometheus
            - name: prom-storage
              mountPath: /prometheus
          {{- with .Values.prometheus.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: prom-config
          configMap:
            name: {{ include "myapp.prometheusCfgName" . }}
        - name: prom-storage
          emptyDir: {}
{{- end }}

