{{- if and .Values.prometheus.enabled .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "myapp.componentName" (dict "root" . "component" "servicemonitor") }}
  labels:
    {{- include "myapp.componentLabels" (dict "root" . "component" "monitoring") | nindent 4 }}
    release: {{ .Release.Name }}
    monitoring: "app"
spec:
  selector:
    matchLabels:
      {{- include "myapp.componentSelectorLabels" (dict "root" . "component" "app") | nindent 6 }}

  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  

  endpoints:
    - interval: {{ .Values.prometheus.serviceMonitor.interval }}
      port: http
      path: {{ .Values.prometheus.serviceMonitor.path }}
{{- end }}